# Generated by Django 2.1.5 on 2019-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=255)),
                ('opening_milage', models.IntegerField()),
                ('closing_milage', models.IntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('comments', models.TextField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
